### ISSUE TITLE
Sidebar disappears in small browser windows

### ISSUE THREAD

**Issue by tobanw** [swanson/lagom#22]
If you resize your browser viewport to be smaller (or visit the site on mobile), the sidebar is hidden so that the main content gets the entire screen (this is good). However, all of the sidebar content is inaccessible, so there's no way for users to navigate using the sidebar links, for example.

A simple solution would be to have the sidebar content show up beneath the content.

**Comment by swanson** [comment]
The sidebar disappearing was intentional - I'd be open to changing it to show beneath the content or elsewhere if you are interested in opening a PR.

Might be best to start with a mockup just to see how it will look.

**Comment by jawadnassar** [comment]
i faced the same issue, what i wanted to do:
1- homepage shows the sidebar first then the blog posts
2- when reading a blog, the sidebar is hidden

I ended up doing a small hack, all main pages use a  css file different than the one used in blog posts.
check out my repo for a demo.

**Comment by mrjk05** [comment]
@jawadnassar could you post your hack? I too would like to have a mini sidebar like a floating menu when reading on smaller screens (i.e. phones)

**Comment by jawadnassar** [comment]
this is probably too late, but might be handy for other people; I created a new CSS file and a new layout.
Kindly check the commit under https://github.com/jawadnassar/jawadnassar.github.io/commit/9c992515d58a182a399f72862eacdddbb330955b

**Comment by swanson** [comment]
Thanks @jawadnassar -- if folks are interested in changing the layout, I think getting your hands dirty and tweaking the CSS/layout is the best way forward.
