### ISSUE TITLE
Mobile Layout Readability Issue

### ISSUE THREAD

**Issue by 2210923402** [swanson/lagom#28]
Hi Matt,

Thank you for providing the Lagom theme to the public; it's sleek without sacrificing functionality, I love it.

I just have one thing I wanted to change. On mobile, the post title begins in the same line as the date without a line break, making for a jagged read (image attached). I was wondering how I can go about having the date and post title on separate lines, on mobile only, without affecting the desktop rendering (date and title on same lines). Any advice would be greatly appreciated.

![image](https://cloud.githubusercontent.com/assets/13086831/11308119/5922a0e2-8f8a-11e5-84a1-bf29cd7899fc.png)

**Comment by swanson** [comment]
You can find mobile-specific styles here: https://github.com/swanson/lagom/blob/master/_includes/css/layout.css#L11-L17

You could add a rule like this:

```css
#blog-posts span {
  display: block;
}
```

**Comment by 2210923402** [comment]
Thank you!
