### ISSUE TITLE
How to justify the text in posts

### ISSUE THREAD

**Issue by sidtechnical** [swanson/lagom#29]
Hi,

How can I justify the texts in my posts? I used several trips and tricks available over the Internet. Nothing seems to work as something is overriding my tiny-weeny scripts. 

Possibly also suggest me, how can I change the properties of my text (such as font size and style)

http://sidtechnical.github.io/

**Comment by swanson** [comment]
Not sure I completely understand what you are asking.

Adding this to the `screen.css` will justify the text:

```css
#post {
 text-align: justify;
}
```

You can modify any of the styles (font size, color, etc) either in that file directly, or add a new css file to `_includes/css` and then make sure to put a new entry in `assets/css/all.css` for it to be included when the site is built.

**Comment by sidtechnical** [comment]
Thanks a lot. I was tweaking the wrong css. Adding the text-align in screen.css solved the issue.
