### ISSUE TITLE
Incorrect Time

### ISSUE THREAD

**Issue by daumie** [swanson/lagom#32]
Time not rendered correctly on deploying.
After writing an article and posting it, time displayed still shows 2013....etc

**Comment by swanson** [comment]
Hey there, I've had a look at: https://github.com/daumie/daumie.github.io/tree/master/_posts

The date comes from the title of the markdown files, not when the post is written. So it looks like 3 of the 4 posts have dates in 2013 (`2013-08-12-installing-git-on-linux.md`, `2013-08-12-up-and-running-weechat.md`, `2013-08-20-up-and-running -with-jekyll.md`). You can update the file name to use the correct and restart Jekyll and you should see the change.

**Comment by daumie** [comment]
Thanks ......worked fine
