### ISSUE TITLE
Add tags to posts

### ISSUE THREAD

**Issue by clearnote01** [swanson/lagom#39]
I believe it would be great if we could have a feature to add tags to blog posts. And then view all the tags at one place, clicking on which will show all the similar posts.

**Comment by philiplambok** [comment]
this feature doesnt working, its return 404.html when i try to access one of my tags

**Comment by swanson** [comment]
https://github.com/swanson/lagom/pull/52

Please see other solutions like: https://github.com/pattex/jekyll-tagging
http://longqian.me/2017/02/09/github-jekyll-tag/
