### ISSUE TITLE
Logo missing from blog article

### ISSUE THREAD

**Issue by jdvala** [swanson/lagom#45]
I have a problem viewing the image on the sidebar.html while reading the blog article. [https://jdvala.github.io/git_pages/](Blog). Please look into it

Have tried almost everything but I am unable to make it work.

**Comment by swanson** [comment]
Try adding a "/" at the start of the `src` tag in https://github.com/jdvala/git_pages/blob/master/docs/_includes/sidebar.html#L7

`<img src="blog_logo.jpg"` -> `<img src="/blog_logo.jpg"`

On pages other than the homepage, the path is not correct.
